### ISSUE TITLE
android 2.3上文字画不出来

### ISSUE THREAD

**Issue by ty44795016** [cctanfujun/ProgressRoundButton#3]
进度条上的文字绘制不出来

**Comment by cctanfujun** [comment]
library的minsdk是14 说明这个项目在4.0以上版本应该正常运行 按照现在的Android版本覆盖率已经不需要再对4.0以下进行兼容

**Comment by ty44795016** [comment]
想咨询下2.3.6上无法运行的原因是什么

**Comment by cctanfujun** [comment]
低版本的api实现不一样 你可以考虑关闭硬件加速试试

发自 网易邮箱大师
On 06/05/2016 15:39, ty44795016 wrote:
想咨询下2.3.6上无法运行的原因是什么

**Comment by ty44795016** [comment]
尝试过关闭硬件加速，没什么效果。

**Comment by ty44795016** [comment]
背景进度条是正常绘制的，只有上面的文字绘制不出来，感觉很奇怪。。。

**Comment by cctanfujun** [comment]
那我就不知道了 没有详细研究

发自 网易邮箱大师
On 06/05/2016 15:54, ty44795016 wrote:
背景进度条是正常绘制的，只有上面的文字绘制不出来，感觉很奇怪。。。

**Comment by ty44795016** [comment]
好的，谢谢
