### ISSUE TITLE
getProgress() return wrong first run?

### ISSUE THREAD

**Issue by AndroidLTG** [cctanfujun/ProgressRoundButton#4]
Hi! I really like this library but i got a problem.

First run, I set progress text like :

>  button.setProgressText("Loading", intCount); // intCount = 100 here.

After i check the progress like :

>   if (button.getProgress() >= 100) {
>      //Do something
>      }

But when debug button.getProgress() return not 100 .

And Second run this working perfect (this return 100)!

What is the problem here?

**Comment by cctanfujun** [comment]
this is a Bug,i have  fix it in 1.1.0,Thank you for your attention
